services:
  pritunl:
    image: jippi/pritunl:latest
    container_name: pritunl-vpn
    restart: always
    environment:
      - MONGO_URI=mongodb://mongo:27017/pritunl
    ports:
      - "1194:1194/udp"  # OpenVPN порт
      - "9700:9700/tcp"  # Pritunl веб интерфейс
    networks:
      - vpn-net
    volumes:
      - pritunl-data:/var/lib/pritunl
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pritunl.rule=Host(`vpn.uni-play.ru`)"
      - "traefik.http.routers.pritunl.entrypoints=websecure"
      - "traefik.http.routers.pritunl.tls=true"
      - "traefik.http.routers.pritunl.service=pritunl-vpn"
      - "traefik.http.services.pritunl-vpn.loadbalancer.server.port=9700" # Порт веб-интерфейса Pritunl

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    volumes:
      - mongo-data:/data/db
    networks:
      - vpn-net

  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    command:
      - "--api.insecure=true"  # Traefik веб интерфейс
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=ssssargsian@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--log.level=INFO"  # Включение логирования
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Порт для Traefik веб интерфейса
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`vpn.uni-play.ru`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=myresolver"
      - "traefik.http.routers.traefik.service=api@internal" # Traefik dashboard

networks:
  vpn-net:
    name: vpn-net

volumes:
  pritunl-data:
  mongo-data:
  letsencrypt: